import fs from'node:fs';import assert from'node:assert/strict';
const src=fs.readFileSync(new URL('../src/components/WilpayAttachmentLink.jsx',import.meta.url),'utf8');
assert.match(src,/openWilpayAttachmentForCurrentSession/,'component must use authenticated viewer session');
assert.match(src,/e\.preventDefault\(\)/,'component must not navigate directly');
assert.match(src,/record\.record_type==='ATTACHMENT'/,'viewer link must only accept attachment records');
assert.match(src,/disabled=\{busy\|\|!canOpen\}/,'component must block duplicate, empty and non-attachment opens');
assert.match(src,/aria-busy=\{busy\?'true':'false'\}/,'component must expose viewer busy state');
assert.match(src,/role="alert"/,'viewer failures must be visible to the user');
assert.doesNotMatch(src,/href=\{record\.data_url\}/,'component must not expose direct legacy/private href');
console.log('PASS wilpayAttachmentLink');
