import React,{useEffect,useMemo,useState}from'react';
import{neon}from'./lib/aureonClient';

const ADMIN_EMAIL='admin@wilpay.com.br';
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+Number(n||0));return x.toISOString().slice(0,10)};
const addHours=(d,n)=>new Date(new Date(d).getTime()+Number(n||0)*3600000).toISOString();
const fmtDate=v=>v?new Date(String(v).slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const fmtDateTime=v=>v?new Date(v).toLocaleString('pt-BR'):'—';
const grade=s=>{const n=Number(s||0);return n>=850?'A':n>=700?'B':n>=550?'C':n>=400?'D':'E'};
const gradeText=s=>({A:'Excelente',B:'Muito bom',C:'Em evolução',D:'Atenção',E:'Inicial'})[grade(s)];
const defaults={id:1,min_amount:100,max_amount:10000,default_interest_rate:12,payout_sla_hours:24};
const activeStatuses=['EM_ANALISE','APROVADO_AGUARDANDO_PIX','PIX_ENVIADO','ATIVO'];
const baseDocTypes=['DOCUMENTO_FOTO','COMPROVANTE_RESIDENCIA','SELFIE_DOCUMENTO'];
const guaranteeDocTypes=['GARANTIA_FOTO_1','GARANTIA_FOTO_2','GARANTIA_FOTO_3'];
const docTitle=t=>({DOCUMENTO_FOTO:'Documento com foto',COMPROVANTE_RESIDENCIA:'Comprovante de residência',SELFIE_DOCUMENTO:'Selfie com documento',GARANTIA_FOTO_1:'Garantia · foto 1',GARANTIA_FOTO_2:'Garantia · foto 2',GARANTIA_FOTO_3:'Garantia · foto 3',COMPROVANTE_PAGAMENTO:'Comprovante da liberação'})[t]||String(t||'Documento').replaceAll('_',' ');

function Logo(){return <div className="brandmark">W</div>}

async function compactFile(file,targetBytes=105*1024){
  if(!file)throw new Error('Selecione um arquivo.');
  if(file.type==='application/pdf'){
    if(file.size>targetBytes)throw new Error('Esse PDF está grande. Envie uma foto do documento para continuar.');
    return await new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Não foi possível ler o PDF.'));r.onload=()=>resolve({name:file.name,type:file.type,size:file.size,data_url:r.result});r.readAsDataURL(file)});
  }
  if(!String(file.type||'').startsWith('image/'))throw new Error('Envie uma foto JPG/PNG ou um PDF pequeno.');
  const source=await new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Não foi possível ler a imagem.'));r.onload=()=>resolve(r.result);r.readAsDataURL(file)});
  const img=await new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(new Error('Imagem inválida.'));i.src=source});
  let maxSide=1600,quality=.82,result='';
  for(let round=0;round<7;round++){
    const scale=Math.min(1,maxSide/Math.max(img.width,img.height));
    const w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));
    const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);
    for(let q=quality;q>=.42;q-=.08){
      result=c.toDataURL('image/jpeg',q);
      const bytes=Math.ceil((result.split(',')[1]?.length||0)*.75);
      if(bytes<=targetBytes)return{name:file.name.replace(/\.[^.]+$/,'.jpg'),type:'image/jpeg',size:bytes,data_url:result};
    }
    maxSide=Math.round(maxSide*.82);
  }
  const bytes=Math.ceil((result.split(',')[1]?.length||0)*.75);
  if(bytes>170*1024)throw new Error('Não consegui compactar essa foto. Tente outra imagem.');
  return{name:file.name.replace(/\.[^.]+$/,'.jpg'),type:'image/jpeg',size:bytes,data_url:result};
}

function Auth({onReady}){
  const[mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const admin=form.email.trim().toLowerCase()===ADMIN_EMAIL;
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=mode==='register'?await neon.auth.signUp.email({name:form.name,email:form.email,password:form.password}):await neon.auth.signIn.email({email:form.email,password:form.password});if(r.error)throw new Error(r.error.message);await onReady()}catch(err){setError(err.message||'Não foi possível entrar.')}finally{setBusy(false)}}
  return <div className="auth-page"><div className="auth-hero"><Logo/><h1>W.I.L PAY</h1><p>Crédito direto, análise simples e acompanhamento em tempo real.</p></div><form className="auth-card" onSubmit={submit}><small>{admin?'CENTRAL ADMINISTRATIVA':'ACESSO W.I.L'}</small><h2>{mode==='login'?'Entrar':'Criar conta'}</h2>{!admin&&<div className="seg"><button type="button" className={mode==='login'?'on':''} onClick={()=>setMode('login')}>Entrar</button><button type="button" className={mode==='register'?'on':''} onClick={()=>setMode('register')}>Criar conta</button></div>}{mode==='register'&&!admin&&<label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label>}<label>E-mail<input required type="email" value={form.email} onChange={e=>{const email=e.target.value;setForm({...form,email});if(email.trim().toLowerCase()===ADMIN_EMAIL)setMode('login')}}/></label><label>Senha<input required type="password" minLength="10" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Aguarde...':admin?'Entrar na Central':mode==='login'?'Entrar':'Começar agora'}</button><p className="safe">Conta protegida pela Aureon Base.</p></form></div>
}

export default function App(){
  const[user,setUser]=useState(null),[loading,setLoading]=useState(true);
  async function session(){const s=await neon.auth.getSession();setUser(s.data?.user||null);setLoading(false)}
  useEffect(()=>{session()},[]);
  if(loading)return <div className="splash"><Logo/><b>W.I.L PAY</b></div>;
  if(!user)return <Auth onReady={session}/>;
  return user.email?.toLowerCase()===ADMIN_EMAIL?<AdminApp authUser={user}/>:<ClientApp authUser={user}/>;
}

function Shell({admin,email,onSignOut,children}){return <div className="app"><header className="app-header"><div className="head-row"><div className="brand"><Logo/><div><b>W.I.L PAY</b><small>{admin?'ADMINISTRADOR':email}</small></div></div><button className="ghost" onClick={onSignOut}>Sair</button></div><div className="headline"><small>{admin?'CENTRAL W.I.L':'CRÉDITO SEM ENROLAÇÃO'}</small><h1>{admin?'Carteira, análise e cobrança.':'Responda. Envie. Acompanhe.'}</h1><p>{admin?'Veja clientes, documentos, localização, liberações, recebimentos e lucro em uma única visão.':'Quiz rápido, documentos e localização. O PIX só é pedido depois da aprovação.'}</p></div></header>{children}</div>}
function ScoreCard({score=500}){const g=grade(score);return <section className="score-card"><div><small>W.I.L SCORE</small><h2>{score}<span>/1000</span></h2><p>{gradeText(score)}</p></div><div className={`grade grade-${g}`}>{g}</div><div className="score-line"><i style={{width:`${clamp(score,1,1000)/10}%`}}/></div><div className="grade-scale"><span>E</span><span>D</span><span>C</span><span>B</span><span>A</span></div></section>}
function statusLabel(status){return({EM_ANALISE:'Em análise',APROVADO_AGUARDANDO_PIX:'Aprovado · envie o PIX',PIX_ENVIADO:'PIX enviado · aguardando liberação',ATIVO:'Crédito liberado',RECUSADO:'Não aprovado',PAGO:'Quitado'})[status]||'Começar'}
function FlowSteps({status}){const step=({EM_ANALISE:4,APROVADO_AGUARDANDO_PIX:5,PIX_ENVIADO:6,ATIVO:7,PAGO:8,RECUSADO:0})[status]||1,items=['Quiz','Documentos','Garantia','Localização','Análise','PIX','Liberação','Pagamento'];return <div className="flow-steps v3steps">{items.map((t,i)=><div className={step>i?'done':step===i?'current':''} key={t}><b>{step>i?'✓':i+1}</b><span>{t}</span></div>)}</div>}

const isLoanRow=r=>!r.record_type||r.record_type==='LOAN';
const isAttachment=r=>r.record_type==='ATTACHMENT';
const isLocation=r=>r.record_type==='LOCATION';

function ClientApp({authUser}){
  const[tab,setTab]=useState('inicio'),[profile,setProfile]=useState({name:authUser.name||authUser.email,score:500}),[rows,setRows]=useState([]),[payments,setPayments]=useState([]),[settings,setSettings]=useState(defaults),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[pix,setPix]=useState('');
  const loans=rows.filter(isLoanRow).sort((a,b)=>new Date(b.requested_at||b.created_at)-new Date(a.requested_at||a.created_at)),attachments=rows.filter(isAttachment),locations=rows.filter(isLocation),current=loans[0];
  async function load(){setBusy(true);try{let p=await neon.from('wilpay_profiles').select('*').eq('auth_uid',authUser.id).limit(1),row=p.data?.[0];if(!row){const i=await neon.from('wilpay_profiles').insert({auth_uid:authUser.id,email:authUser.email,name:authUser.name||authUser.email,score:500,member_since:new Date().toISOString()}).select();row=i.data?.[0]||{name:authUser.email,score:500}}setProfile(row);const[r,pa,s]=await Promise.all([neon.from('wilpay_loans').select('*').eq('auth_uid',authUser.id).order('created_at',{ascending:false}),neon.from('wilpay_payments').select('*').eq('auth_uid',authUser.id).order('due_date'),neon.from('wilpay_settings').select('*').eq('id',1).limit(1)]);setRows(r.data||[]);setPayments(pa.data||[]);if(s.data?.[0])setSettings({...defaults,...s.data[0]})}finally{setBusy(false)}}
  useEffect(()=>{load()},[]);
  async function sendPix(){if(!current||!pix.trim())return;setBusy(true);const now=new Date().toISOString(),deadline=addHours(now,settings.payout_sla_hours||24);const r=await neon.from('wilpay_loans').update({pix_key:pix.trim(),pix_submitted_at:now,payout_deadline_at:deadline,status:'PIX_ENVIADO'}).eq('id',current.id).select();if(!r.error){await neon.from('wilpay_profiles').update({pix_key:pix.trim(),updated_at:now}).eq('auth_uid',authUser.id);setNotice(`PIX enviado. Prazo de liberação: até ${fmtDateTime(deadline)}.`);await load()}else setNotice(r.error.message);setBusy(false)}
  async function signOut(){await neon.auth.signOut();location.reload()}
  const canApply=!loans.some(x=>activeStatuses.includes(x.status));
  const receipt=attachments.find(d=>String(d.loan_id)===String(current?.id)&&d.doc_type==='COMPROVANTE_PAGAMENTO');
  return <Shell email={authUser.email} onSignOut={signOut}><main className="client-main">{notice&&<div className="notice">{notice}</div>}{tab==='inicio'&&<><ScoreCard score={profile.score}/><FlowSteps status={current?.status}/>{current?<section className="status-card"><small>STATUS ATUAL</small><h2>{statusLabel(current.status)}</h2><p>Solicitação #{current.id} · {brl(current.principal)}</p>{current.status==='EM_ANALISE'&&!current.submission_complete&&<div className="error">Esta solicitação antiga ficou incompleta. Peça ao administrador para excluí-la e envie novamente.</div>}{current.status==='APROVADO_AGUARDANDO_PIX'&&<div className="pix-box"><h3>Crédito aprovado</h3><p>Agora informe a chave PIX que receberá o valor.</p><input placeholder="CPF, celular, e-mail ou chave aleatória" value={pix} onChange={e=>setPix(e.target.value)}/><button className="primary" disabled={busy||!pix.trim()} onClick={sendPix}>Enviar PIX para o administrador</button></div>}{current.status==='PIX_ENVIADO'&&<div className="deadline"><b>PIX recebido</b><span>Prazo para liberação: {fmtDateTime(current.payout_deadline_at)}</span></div>}{current.status==='ATIVO'&&<div className="released"><b>Valor liberado</b><span>Pagamento fixo em 2x: +15 e +30 dias.</span>{receipt&&<a href={receipt.data_url} target="_blank" rel="noreferrer">Ver comprovante da liberação</a>}</div>}{current.status==='RECUSADO'&&<button className="secondary" onClick={()=>setTab('solicitar')}>Fazer nova solicitação</button>}</section>:<section className="start-card"><small>COMECE AQUI</small><h2>Descubra seu crédito em poucos passos.</h2><p>O PIX só é solicitado depois que você for aprovado.</p><button className="primary" onClick={()=>setTab('solicitar')}>Solicitar análise</button></section>}<div className="quick-grid"><button onClick={()=>setTab('pagamentos')}><b>Pagamentos</b><small>2 parcelas e datas</small></button><button onClick={()=>setTab('perfil')}><b>Meu cadastro</b><small>Dados pessoais</small></button></div></>}{tab==='solicitar'&&<ApplicationWizard authUser={authUser} settings={settings} canApply={canApply} onDone={async()=>{setTab('inicio');await load()}} setNotice={setNotice}/>} {tab==='pagamentos'&&<Payments payments={payments}/>} {tab==='perfil'&&<Profile profile={profile} authUser={authUser} onSaved={async()=>{setNotice('Cadastro atualizado.');await load()}}/>}</main><nav className="bottom-nav">{[['inicio','Início'],['solicitar','Solicitar'],['pagamentos','Pagamentos'],['perfil','Perfil']].map(([id,t])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{t}</button>)}</nav></Shell>
}

function ApplicationWizard({authUser,settings,canApply,onDone,setNotice}){
  const[step,setStep]=useState(0),[stage,setStage]=useState('quiz'),[busy,setBusy]=useState(false),[fileError,setFileError]=useState(''),[locationAccepted,setLocationAccepted]=useState(false),[locationPoint,setLocationPoint]=useState(null),[locating,setLocating]=useState(false),[files,setFiles]=useState({documento:null,residencia:null,selfie:null}),[collateral,setCollateral]=useState({description:'',value:'',photo1:null,photo2:null,photo3:null});
  const[a,setA]=useState({amount:Math.max(Number(settings.min_amount||100),1000),purpose:'',income_type:'',monthly_income:'',income_time:'',open_debts:'',work_contact_name:'',work_contact_phone:'',family_contact_name:'',family_contact_phone:''});
  const collateralRequired=Number(a.amount)>1000;
  const questions=[{key:'amount',title:'Quanto você precisa?',render:<><div className="money-big">{brl(a.amount)}</div><input type="range" min={settings.min_amount||100} max={settings.max_amount||10000} step="100" value={a.amount} onChange={e=>setA({...a,amount:+e.target.value})}/></>},{key:'purpose',title:'Para que você pretende usar o crédito?',options:['Emergência','Organizar contas','Compra pessoal','Negócio / trabalho','Outro']},{key:'income_type',title:'Qual é sua principal fonte de renda?',options:['CLT','Autônomo','Empresário','Aposentadoria / benefício','Outra']},{key:'monthly_income',title:'Qual sua renda mensal aproximada?',render:<input className="big-input" type="number" min="0" placeholder="Ex.: 3500" value={a.monthly_income} onChange={e=>setA({...a,monthly_income:e.target.value})}/>},{key:'income_time',title:'Há quanto tempo você recebe dessa fonte?',options:['Menos de 3 meses','3 a 6 meses','6 a 12 meses','Mais de 12 meses']},{key:'open_debts',title:'Você possui parcelas ou empréstimos em aberto?',options:['Não','Sim']},{key:'work',title:'Informe 1 contato do trabalho',render:<div className="contact-fields"><input className="big-input" placeholder="Nome do contato" value={a.work_contact_name} onChange={e=>setA({...a,work_contact_name:e.target.value})}/><input className="big-input" type="tel" placeholder="Telefone / WhatsApp" value={a.work_contact_phone} onChange={e=>setA({...a,work_contact_phone:e.target.value})}/></div>},{key:'family',title:'Informe 1 contato da família',render:<div className="contact-fields"><input className="big-input" placeholder="Nome do familiar" value={a.family_contact_name} onChange={e=>setA({...a,family_contact_name:e.target.value})}/><input className="big-input" type="tel" placeholder="Telefone / WhatsApp" value={a.family_contact_phone} onChange={e=>setA({...a,family_contact_phone:e.target.value})}/></div>}];
  const q=questions[Math.min(step,questions.length-1)];
  const valid=()=>q.key==='amount'?Number(a.amount)>0:q.key==='work'?a.work_contact_name.trim()&&a.work_contact_phone.trim():q.key==='family'?a.family_contact_name.trim()&&a.family_contact_phone.trim():String(a[q.key]||'').trim();
  function choose(v){setA({...a,[q.key]:v});setTimeout(()=>setStep(s=>Math.min(s+1,questions.length-1)),100)}
  async function readDoc(key,file){setFileError('');try{const x=await compactFile(file);setFiles(v=>({...v,[key]:x}))}catch(err){setFileError(err.message)}}
  async function readGuarantee(key,file){setFileError('');try{const x=await compactFile(file);setCollateral(v=>({...v,[key]:x}))}catch(err){setFileError(err.message)}}
  async function captureLocation(){setFileError('');if(!locationAccepted){setFileError('Marque a autorização de localização para continuar.');return}if(!navigator.geolocation){setFileError('Este aparelho não disponibilizou localização.');return}setLocating(true);navigator.geolocation.getCurrentPosition(pos=>{setLocationPoint({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,captured_at:new Date().toISOString()});setLocating(false)},()=>{setFileError('Libere a permissão de localização do navegador para continuar.');setLocating(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
  async function saveAttachment(loan,docType,doc,now){return await neon.from('wilpay_loans').insert({record_type:'ATTACHMENT',auth_uid:authUser.id,loan_id:loan.id,doc_type:docType,file_name:doc.name,mime_type:doc.type,size:doc.size,data_url:doc.data_url,created_at:now}).select()}
  async function cleanup(loanId){await neon.from('wilpay_loans').delete().eq('loan_id',loanId);await neon.from('wilpay_loans').delete().eq('id',loanId)}
  async function submit(){
    if(!canApply){setNotice('Você já possui uma análise ou crédito em andamento.');return}
    if(!files.documento||!files.residencia||!files.selfie){setFileError('Envie os 3 documentos para continuar.');return}
    if(collateralRequired&&(!collateral.description.trim()||!Number(collateral.value)||!collateral.photo1||!collateral.photo2||!collateral.photo3)){setFileError('Acima de R$ 1.000 é obrigatório informar a garantia e enviar as 3 fotos.');return}
    if(!locationAccepted||!locationPoint){setFileError('Autorize e confirme sua localização antes de pedir análise.');return}
    setBusy(true);setFileError('');const now=new Date().toISOString(),rate=Number(settings.default_interest_rate||12),total=Number(a.amount)*(1+rate/100);
    const created=await neon.from('wilpay_loans').insert({record_type:'LOAN',auth_uid:authUser.id,principal:Number(a.amount),total_amount:Number(total.toFixed(2)),interest_rate:rate,status:'EM_ANALISE',repayment_type:'2X_QUINZENAL',installment_count:2,term_days:15,requested_at:now,answers:a,collateral_required:collateralRequired,collateral_description:collateralRequired?collateral.description:'',collateral_declared_value:collateralRequired?Number(collateral.value):0,submission_complete:false}).select();
    if(created.error||!created.data?.[0]){setFileError(created.error?.message||'Não foi possível criar a análise.');setBusy(false);return}
    const loan=created.data[0];
    try{
      const docs=[['DOCUMENTO_FOTO',files.documento],['COMPROVANTE_RESIDENCIA',files.residencia],['SELFIE_DOCUMENTO',files.selfie]];
      if(collateralRequired)docs.push(['GARANTIA_FOTO_1',collateral.photo1],['GARANTIA_FOTO_2',collateral.photo2],['GARANTIA_FOTO_3',collateral.photo3]);
      for(const[type,doc]of docs){const r=await saveAttachment(loan,type,doc,now);if(r.error)throw new Error(`Falha ao salvar ${docTitle(type)}: ${r.error.message}`)}
      const loc=await neon.from('wilpay_loans').insert({record_type:'LOCATION',auth_uid:authUser.id,loan_id:loan.id,...locationPoint,consent:true,purpose:'Análise cadastral e prevenção a fraude',created_at:now}).select();if(loc.error)throw new Error(`Falha ao salvar localização: ${loc.error.message}`);
      const done=await neon.from('wilpay_loans').update({submission_complete:true,documents_ready:true,location_ready:true}).eq('id',loan.id).select();if(done.error)throw new Error(done.error.message);
      setNotice('Análise enviada com documentos, contatos e localização confirmados.');setBusy(false);await onDone();
    }catch(err){await cleanup(loan.id);setFileError(`${err.message}. A solicitação não foi enviada; tente novamente.`);setBusy(false)}
  }
  if(!canApply)return <section className="wizard"><small>SOLICITAÇÃO</small><h2>Você já tem uma etapa em andamento.</h2><p>Conclua ou exclua a solicitação atual antes de iniciar outra.</p></section>;
  if(stage==='quiz')return <section className="wizard"><div className="wizard-top"><span>PERGUNTA {step+1} DE {questions.length}</span><b>{Math.round(((step+1)/questions.length)*100)}%</b></div><div className="progress"><i style={{width:`${((step+1)/questions.length)*100}%`}}/></div><h2>{q.title}</h2>{q.render||<div className="option-list">{q.options.map(o=><button key={o} className={a[q.key]===o?'selected':''} onClick={()=>{setA({...a,[q.key]:o});if(step<questions.length-1)setStep(step+1)}}>{o}</button>)}</div>}{q.render&&<div className="wizard-actions">{step>0&&<button className="secondary" onClick={()=>setStep(step-1)}>Voltar</button>}<button className="primary" disabled={!valid()} onClick={()=>step===questions.length-1?setStage('documents'):setStep(step+1)}>Continuar</button></div>}{!q.render&&step>0&&<button className="back-link" onClick={()=>setStep(step-1)}>← Voltar</button>}</section>;
  if(stage==='documents')return <section className="wizard"><small>DOCUMENTOS</small><h2>Envie os 3 documentos.</h2><p>As fotos são compactadas automaticamente e ficam visíveis no ADM.</p><div className="doc-grid"><DocUpload title="Documento com foto" hint="RG ou CNH" file={files.documento} onFile={f=>readDoc('documento',f)}/><DocUpload title="Comprovante de residência" hint="Conta recente" file={files.residencia} onFile={f=>readDoc('residencia',f)}/><DocUpload title="Selfie com documento" hint="Rosto e documento visíveis" file={files.selfie} onFile={f=>readDoc('selfie',f)}/></div>{fileError&&<div className="error">{fileError}</div>}<div className="wizard-actions"><button className="secondary" onClick={()=>{setStage('quiz');setStep(questions.length-1)}}>Voltar</button><button className="primary" disabled={!files.documento||!files.residencia||!files.selfie} onClick={()=>setStage(collateralRequired?'collateral':'location')}>Continuar</button></div></section>;
  if(stage==='collateral')return <section className="wizard collateral-step"><small>GARANTIA OBRIGATÓRIA</small><h2>Pedido acima de R$ 1.000.</h2><p>Informe o bem e envie 3 fotos. O ADM define o valor que será liberado e o dinheiro só sai depois que a garantia estiver fisicamente em mãos.</p><label className="field">Descrição da garantia<input placeholder="Ex.: notebook, celular, TV..." value={collateral.description} onChange={e=>setCollateral({...collateral,description:e.target.value})}/></label><label className="field">Valor estimado da garantia<input type="number" min="1" placeholder="Ex.: 2500" value={collateral.value} onChange={e=>setCollateral({...collateral,value:e.target.value})}/></label><div className="doc-grid"><DocUpload title="Foto 1 da garantia" hint="Visão geral" file={collateral.photo1} onFile={f=>readGuarantee('photo1',f)}/><DocUpload title="Foto 2 da garantia" hint="Detalhes" file={collateral.photo2} onFile={f=>readGuarantee('photo2',f)}/><DocUpload title="Foto 3 da garantia" hint="Outra visão" file={collateral.photo3} onFile={f=>readGuarantee('photo3',f)}/></div><div className="guarantee-warning"><b>Liberação bloqueada</b><span>Até o ADM confirmar que recebeu a garantia em mãos.</span></div>{fileError&&<div className="error">{fileError}</div>}<div className="wizard-actions"><button className="secondary" onClick={()=>setStage('documents')}>Voltar</button><button className="primary" disabled={!collateral.description.trim()||!Number(collateral.value)||!collateral.photo1||!collateral.photo2||!collateral.photo3} onClick={()=>setStage('location')}>Continuar</button></div></section>;
  return <section className="wizard"><small>LOCALIZAÇÃO OBRIGATÓRIA</small><h2>Confirme sua localização.</h2><p>O ponto atual é usado nesta análise cadastral e fica visível ao administrador.</p><label className="location-consent"><input type="checkbox" checked={locationAccepted} onChange={e=>{setLocationAccepted(e.target.checked);if(!e.target.checked)setLocationPoint(null)}}/><span><b>Autorizo o uso da minha localização atual nesta análise.</b><small>Sem essa confirmação a análise não é enviada.</small></span></label><button className="secondary location-btn" disabled={!locationAccepted||locating} onClick={captureLocation}>{locating?'Obtendo localização...':locationPoint?'✓ Localização confirmada':'Confirmar localização agora'}</button>{locationPoint&&<div className="location-ok"><b>Localização registrada</b><small>Precisão aproximada: {Math.round(locationPoint.accuracy||0)} m</small></div>}{fileError&&<div className="error">{fileError}</div>}<div className="review-mini"><b>Resumo</b><span>Valor: {brl(a.amount)}</span><span>Trabalho: {a.work_contact_name} · {a.work_contact_phone}</span><span>Família: {a.family_contact_name} · {a.family_contact_phone}</span><span>{collateralRequired?'Garantia obrigatória · 3 fotos':'Sem garantia até R$ 1.000'}</span><span>Pagamento: 2x · +15 e +30 dias</span></div><div className="wizard-actions"><button className="secondary" onClick={()=>setStage(collateralRequired?'collateral':'documents')}>Voltar</button><button className="primary" disabled={busy||!locationPoint} onClick={submit}>{busy?'Validando e enviando...':'Pedir análise'}</button></div></section>;
}

function DocUpload({title,hint,file,onFile}){return <label className={file?'doc-upload uploaded':'doc-upload'}><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>onFile(e.target.files?.[0])}/><b>{file?'✓ '+title:title}</b><small>{file?file.name:hint}</small><span>{file?'Trocar arquivo':'Adicionar arquivo'}</span></label>}
function Payments({payments}){return <section className="panel"><small>PAGAMENTOS</small><h2>Suas parcelas</h2><p className="sub">Padrão fixo: 2 parcelas, com 15 dias entre elas.</p>{payments.length?payments.map(p=><article className="payment-row" key={p.id}><div><b>Parcela {p.installment_number}/2</b><small>Vencimento {fmtDate(p.due_date)}</small></div><div><strong>{brl(p.amount)}</strong><em>{String(p.status||'PENDENTE').replaceAll('_',' ')}</em></div></article>):<div className="empty">As datas aparecem depois da liberação do crédito.</div>}</section>}
function Profile({profile,authUser,onSaved}){const[f,setF]=useState(profile),[busy,setBusy]=useState(false);useEffect(()=>setF(profile),[profile]);async function save(){setBusy(true);const r=await neon.from('wilpay_profiles').update({name:f.name,cpf:f.cpf,phone:f.phone,updated_at:new Date().toISOString()}).eq('auth_uid',authUser.id).select();setBusy(false);if(!r.error)onSaved()}return <section className="panel"><small>MEU CADASTRO</small><h2>Dados essenciais</h2>{[['Nome','name'],['CPF','cpf'],['Telefone','phone']].map(([l,k])=><label className="field" key={k}>{l}<input value={f[k]||''} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<button className="primary" disabled={busy} onClick={save}>{busy?'Salvando...':'Salvar'}</button></section>}

function AdminApp({authUser}){
  const[profiles,setProfiles]=useState([]),[allRows,setAllRows]=useState([]),[payments,setPayments]=useState([]),[settings,setSettings]=useState(defaults),[section,setSection]=useState('painel'),[selected,setSelected]=useState(null),[mapUser,setMapUser]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState({}),[scoreDraft,setScoreDraft]=useState({});
  const loans=allRows.filter(isLoanRow).sort((a,b)=>new Date(b.requested_at||b.created_at)-new Date(a.requested_at||a.created_at)),attachments=allRows.filter(isAttachment),locations=allRows.filter(isLocation);
  async function load(){setBusy(true);const[p,r,pa,s]=await Promise.all([neon.from('wilpay_profiles').select('*').order('created_at',{ascending:false}),neon.from('wilpay_loans').select('*').order('created_at',{ascending:false}),neon.from('wilpay_payments').select('*').order('due_date'),neon.from('wilpay_settings').select('*').eq('id',1).limit(1)]);setProfiles(p.data||[]);setAllRows(r.data||[]);setPayments(pa.data||[]);if(s.data?.[0])setSettings({...defaults,...s.data[0]});setBusy(false)}
  useEffect(()=>{load()},[]);
  const pending=loans.filter(x=>x.status==='EM_ANALISE'),awaitPix=loans.filter(x=>x.status==='APROVADO_AGUARDANDO_PIX'),toPay=loans.filter(x=>x.status==='PIX_ENVIADO'),active=loans.filter(x=>x.status==='ATIVO');
  function profileOf(uid){return profiles.find(p=>p.auth_uid===uid)||{name:'Cliente',score:500,email:''}}
  function docsOf(id){return attachments.filter(d=>String(d.loan_id)===String(id))}
  function locationOf(uid,id){return locations.find(x=>String(x.loan_id)===String(id))||locations.find(x=>x.auth_uid===uid)}
  function readyState(l){const docs=docsOf(l.id),base=baseDocTypes.filter(t=>docs.some(d=>d.doc_type===t)).length,guar=guaranteeDocTypes.filter(t=>docs.some(d=>d.doc_type===t)).length,loc=locationOf(l.auth_uid,l.id);return{base,guar,loc,ok:base===3&&!!loc&&(!l.collateral_required||guar===3)}}
  async function approve(l,value){const state=readyState(l);if(!state.ok){setNotice('Não é possível aprovar: faltam documentos, fotos da garantia ou localização.');return}let approved=Number(l.principal||0);if(l.collateral_required){approved=clamp(Number(value||0),100,Number(l.principal||0));if(!approved){setNotice('Defina o valor que será liberado.');return}}setBusy(true);const rate=Number(settings.default_interest_rate||12),total=approved*(1+rate/100),r=await neon.from('wilpay_loans').update({principal:approved,approved_principal:approved,total_amount:Number(total.toFixed(2)),status:'APROVADO_AGUARDANDO_PIX',approved_at:new Date().toISOString(),interest_rate:rate,repayment_type:'2X_QUINZENAL',installment_count:2,term_days:15}).eq('id',l.id).select();setNotice(r.error?r.error.message:l.collateral_required?`Aprovado em ${brl(approved)}. Receba a garantia em mãos antes da liberação.`:'Aprovado. O cliente já pode informar o PIX.');if(!r.error)setSelected(null);await load();setBusy(false)}
  async function reject(l){if(!confirm('Recusar esta solicitação?'))return;await neon.from('wilpay_loans').update({status:'RECUSADO',rejected_at:new Date().toISOString()}).eq('id',l.id);setNotice('Solicitação recusada.');setSelected(null);load()}
  async function deleteApplication(l){if(!confirm('Excluir esta solicitação e tudo ligado a ela?'))return;setBusy(true);await neon.from('wilpay_loans').delete().eq('loan_id',l.id);await neon.from('wilpay_payments').delete().eq('loan_id',l.id);await neon.from('wilpay_loans').delete().eq('id',l.id);setNotice('Solicitação excluída.');setSelected(null);await load();setBusy(false)}
  async function receiveCollateral(l){if(!confirm('Confirma que a garantia física está em suas mãos?'))return;setBusy(true);const r=await neon.from('wilpay_loans').update({collateral_received_at:new Date().toISOString(),collateral_received_by:ADMIN_EMAIL}).eq('id',l.id).select();setNotice(r.error?r.error.message:'Garantia recebida em mãos. Liberação habilitada.');await load();setBusy(false)}
  async function chooseReceipt(id,file){try{const x=await compactFile(file,105*1024);setReceipt(v=>({...v,[id]:x}))}catch(err){setNotice(err.message)}}
  async function confirmPayout(l){if(l.collateral_required&&!l.collateral_received_at){setNotice('Receba a garantia em mãos antes de liberar o dinheiro.');return}const file=receipt[l.id];if(!file){setNotice('Adicione o comprovante do PIX.');return}setBusy(true);const now=new Date().toISOString(),rate=Number(l.interest_rate||settings.default_interest_rate||12),total=Number(l.principal)*(1+rate/100),part=Number((total/2).toFixed(2));const doc=await neon.from('wilpay_loans').insert({record_type:'ATTACHMENT',auth_uid:l.auth_uid,loan_id:l.id,doc_type:'COMPROVANTE_PAGAMENTO',file_name:file.name,mime_type:file.type,size:file.size,data_url:file.data_url,created_at:now}).select();if(doc.error){setNotice(doc.error.message);setBusy(false);return}const up=await neon.from('wilpay_loans').update({status:'ATIVO',paid_out_at:now,total_amount:Number(total.toFixed(2)),repayment_type:'2X_QUINZENAL',installment_count:2,term_days:15}).eq('id',l.id).select();if(!up.error){const old=await neon.from('wilpay_payments').select('*').eq('loan_id',l.id);if(!old.data?.length){const pa=await neon.from('wilpay_payments').insert([{loan_id:l.id,auth_uid:l.auth_uid,installment_number:1,amount:part,due_date:addDays(now,15),status:'PENDENTE'},{loan_id:l.id,auth_uid:l.auth_uid,installment_number:2,amount:Number((total-part).toFixed(2)),due_date:addDays(now,30),status:'PENDENTE'}]).select();if(pa.error){setNotice(pa.error.message);setBusy(false);return}}setNotice('Liberação confirmada. Parcelas criadas para +15 e +30 dias.');setReceipt(v=>({...v,[l.id]:null}));await load()}else setNotice(up.error.message);setBusy(false)}
  async function markReceived(p){if(p.status!=='PENDENTE')return;setBusy(true);const now=new Date(),due=new Date(String(p.due_date).slice(0,10)+'T23:59:59'),late=now>due,status=late?'PAGO_ATRASADO':'PAGO_NO_PRAZO';await neon.from('wilpay_payments').update({status,paid_at:new Date().toISOString()}).eq('id',p.id);const loanPays=payments.filter(x=>String(x.loan_id)===String(p.loan_id)).map(x=>x.id===p.id?{...x,status}:x),done=loanPays.length===2&&loanPays.every(x=>String(x.status).startsWith('PAGO'));if(done)await neon.from('wilpay_loans').update({status:'PAGO',paid_at:new Date().toISOString()}).eq('id',p.loan_id);const prof=profileOf(p.auth_uid),delta=late?-120:80,bonus=done?100:0,newScore=clamp(Number(prof.score||500)+delta+bonus,1,1000);await neon.from('wilpay_profiles').update({score:newScore,updated_at:new Date().toISOString()}).eq('auth_uid',p.auth_uid);await neon.from('wilpay_score_events').insert({auth_uid:p.auth_uid,loan_id:p.loan_id,payment_id:p.id,points:delta+bonus,reason:late?'Pagamento após vencimento':done?'Pagamento no prazo + ciclo quitado':'Pagamento no prazo',created_at:new Date().toISOString()});setNotice(`Pagamento recebido. Score: ${grade(newScore)} · ${newScore} pontos.`);await load();setBusy(false)}
  async function saveScore(p){const n=clamp(scoreDraft[p.auth_uid]??p.score,1,1000);await neon.from('wilpay_profiles').update({score:n,updated_at:new Date().toISOString()}).eq('auth_uid',p.auth_uid);setNotice(`Score de ${p.name} atualizado para ${grade(n)} · ${n}.`);load()}
  async function deleteClient(p){if(!confirm(`Excluir todos os dados de ${p.name}?`))return;setBusy(true);await neon.from('wilpay_loans').delete().eq('auth_uid',p.auth_uid);await neon.from('wilpay_payments').delete().eq('auth_uid',p.auth_uid);await neon.from('wilpay_score_events').delete().eq('auth_uid',p.auth_uid);await neon.from('wilpay_profiles').delete().eq('auth_uid',p.auth_uid);setNotice('Cliente excluído do W.I.L Pay.');setSelected(null);await load();setBusy(false)}
  async function saveSettings(){const found=await neon.from('wilpay_settings').select('*').eq('id',1).limit(1),payload={...settings,id:1,updated_at:new Date().toISOString()},r=found.data?.[0]?await neon.from('wilpay_settings').update(payload).eq('id',1).select():await neon.from('wilpay_settings').insert(payload).select();setNotice(r.error?r.error.message:'Regras atualizadas.');if(!r.error)load()}
  async function signOut(){await neon.auth.signOut();location.reload()}
  const selectedLoan=loans.find(x=>String(x.id)===String(selected)),mapProfile=profiles.find(p=>p.auth_uid===mapUser),latestByUser=useMemo(()=>{const m={};locations.forEach(x=>{if(!m[x.auth_uid]||new Date(x.captured_at)>new Date(m[x.auth_uid].captured_at))m[x.auth_uid]=x});return m},[locations]),mapPoint=mapUser?latestByUser[mapUser]:null;
  const finance=useMemo(()=>buildFinance(loans,payments),[loans,payments]);
  return <Shell admin email={authUser.email} onSignOut={signOut}><main className="admin-main">{notice&&<div className="notice">{notice}</div>}<div className="admin-tabs">{[['painel','Painel'],['analises',`Análises ${pending.length}`],['liberacoes',`Liberar ${toPay.length}`],['clientes','Clientes'],['mapa','Mapa'],['carteira','Carteira & Lucro'],['pagamentos','Recebimentos'],['regras','Regras']].map(([id,t])=><button key={id} className={section===id?'on':''} onClick={()=>setSection(id)}>{t}</button>)}</div>
  {section==='painel'&&<><section className="kpis"><article><small>EM ANÁLISE</small><b>{pending.length}</b></article><article><small>AGUARDANDO PIX</small><b>{awaitPix.length}</b></article><article><small>PARA LIBERAR</small><b>{toPay.length}</b></article><article><small>CRÉDITO ATIVO</small><b>{active.length}</b></article><article><small>CARTEIRA ATIVA</small><b>{brl(finance.principalOpen)}</b></article><article><small>LUCRO REALIZADO</small><b>{brl(finance.realizedProfit)}</b></article></section><section className="panel wallet-teaser"><div><small>CARTEIRA W.I.L</small><h2>{brl(finance.receivable)}</h2><p>A receber em contratos ativos</p></div><button className="primary" onClick={()=>setSection('carteira')}>Ver carteira e lucro</button></section></>}
  {section==='analises'&&<section className="panel"><small>ANÁLISES</small><h2>Solicitações</h2>{pending.length?pending.map(l=>{const s=readyState(l);return <article className="admin-row" key={l.id}><div><b>{profileOf(l.auth_uid).name}</b><small>{brl(l.principal)} · Score {grade(profileOf(l.auth_uid).score)} · {profileOf(l.auth_uid).score} pts</small><small>{s.base}/3 docs · localização {s.loc?'✓':'—'}{l.collateral_required?` · garantia ${s.guar}/3`:''}</small></div><div><button onClick={()=>setSelected(l.id)}>Abrir ficha</button><button className="danger" onClick={()=>deleteApplication(l)}>Excluir</button></div></article>}):<div className="empty">Nenhuma análise pendente.</div>}</section>}
  {section==='liberacoes'&&<section className="panel"><small>LIBERAÇÕES PIX</small><h2>Clientes aprovados</h2>{toPay.length?toPay.map(l=><article className="payout-card" key={l.id}><div className="payout-top"><div><b>{profileOf(l.auth_uid).name}</b><small>{brl(l.principal)} · Score {grade(profileOf(l.auth_uid).score)} · {profileOf(l.auth_uid).score} pts</small></div><Deadline deadline={l.payout_deadline_at}/></div><div className="pix-copy"><small>CHAVE PIX</small><b>{l.pix_key}</b><button onClick={()=>navigator.clipboard?.writeText(l.pix_key)}>Copiar</button></div>{l.collateral_required&&<div className={l.collateral_received_at?'guarantee-status ok':'guarantee-status'}><small>GARANTIA FÍSICA</small><b>{l.collateral_received_at?'✓ Recebida em mãos':'Aguardando entrega'}</b><span>{l.collateral_description} · {brl(l.collateral_declared_value)}</span>{!l.collateral_received_at&&<button className="secondary" onClick={()=>receiveCollateral(l)}>Confirmar garantia recebida em mãos</button>}</div>}<label className="receipt-upload">Comprovante da transferência<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>chooseReceipt(l.id,e.target.files?.[0])}/><span>{receipt[l.id]?.name||'Adicionar comprovante'}</span></label><button className="primary" disabled={busy||!receipt[l.id]||(l.collateral_required&&!l.collateral_received_at)} onClick={()=>confirmPayout(l)}>Confirmar pagamento e gerar 2 parcelas</button></article>):<div className="empty">Nenhum PIX aguardando liberação.</div>}</section>}
  {section==='clientes'&&<section className="panel"><small>CLIENTES</small><h2>Score e ficha completa</h2><div className="score-legend"><span>A 850–1000</span><span>B 700–849</span><span>C 550–699</span><span>D 400–549</span><span>E 1–399</span></div>{profiles.map(p=><article className="client-row" key={p.auth_uid}><div className={`grade grade-${grade(p.score)}`}>{grade(p.score)}</div><div className="client-info"><b>{p.name}</b><small>{p.email}</small><strong>{p.score||500} pontos · {gradeText(p.score)}</strong><button className="link-btn" onClick={()=>{const l=loans.find(x=>x.auth_uid===p.auth_uid);l?setSelected(l.id):setNotice('Cliente sem solicitação.')}}>Ver ficha completa</button></div><div className="score-edit"><input type="number" min="1" max="1000" value={scoreDraft[p.auth_uid]??p.score??500} onChange={e=>setScoreDraft({...scoreDraft,[p.auth_uid]:e.target.value})}/><button onClick={()=>saveScore(p)}>Salvar score</button><button className="danger" onClick={()=>deleteClient(p)}>Excluir cliente</button></div></article>)}</section>}
  {section==='mapa'&&<section className="panel"><small>MAPA DOS CLIENTES</small><h2>Localizações autorizadas</h2><div className="map-layout"><div className="map-list">{profiles.map(p=><button key={p.auth_uid} className={mapUser===p.auth_uid?'on':''} onClick={()=>setMapUser(p.auth_uid)}><b>{p.name}</b><small>{latestByUser[p.auth_uid]?fmtDateTime(latestByUser[p.auth_uid].captured_at):'Sem ponto'}</small></button>)}</div><div className="map-stage">{mapProfile&&mapPoint?<><h3>{mapProfile.name}</h3><MapView point={mapPoint}/><small>Precisão: {Math.round(mapPoint.accuracy||0)} m · {fmtDateTime(mapPoint.captured_at)}</small></>:<div className="empty">Selecione um cliente com localização registrada.</div>}</div></div></section>}
  {section==='carteira'&&<WalletDashboard finance={finance} loans={loans} payments={payments} profileOf={profileOf}/>} 
  {section==='pagamentos'&&<section className="panel"><small>RECEBIMENTOS</small><h2>Parcelas pendentes</h2>{payments.filter(p=>p.status==='PENDENTE').length?payments.filter(p=>p.status==='PENDENTE').map(p=><article className="payment-admin" key={p.id}><div><b>{profileOf(p.auth_uid).name}</b><small>Parcela {p.installment_number}/2 · vence {fmtDate(p.due_date)}</small></div><strong>{brl(p.amount)}</strong><button className="primary small" disabled={busy} onClick={()=>markReceived(p)}>Confirmar recebimento</button></article>):<div className="empty">Nenhuma parcela pendente.</div>}</section>}
  {section==='regras'&&<section className="panel"><small>REGRAS</small><h2>Configuração</h2><div className="settings-grid"><label>Crédito mínimo<input type="number" value={settings.min_amount} onChange={e=>setSettings({...settings,min_amount:+e.target.value})}/></label><label>Crédito máximo<input type="number" value={settings.max_amount} onChange={e=>setSettings({...settings,max_amount:+e.target.value})}/></label><label>Juros padrão (%)<input type="number" step="0.01" value={settings.default_interest_rate} onChange={e=>setSettings({...settings,default_interest_rate:+e.target.value})}/></label><label>Prazo do ADM para pagar (horas)<input type="number" min="1" max="168" value={settings.payout_sla_hours} onChange={e=>setSettings({...settings,payout_sla_hours:+e.target.value})}/></label></div><div className="fixed-rule"><b>Pagamento do cliente</b><span>2 parcelas · 1ª em 15 dias · 2ª em 30 dias</span></div><div className="fixed-rule"><b>Garantia</b><span>Acima de R$ 1.000 · 3 fotos · liberação só após recebimento físico</span></div><button className="primary" onClick={saveSettings}>Salvar regras</button></section>}
  {selectedLoan&&<ClientFileModal loan={selectedLoan} profile={profileOf(selectedLoan.auth_uid)} docs={docsOf(selectedLoan.id)} point={locationOf(selectedLoan.auth_uid,selectedLoan.id)} busy={busy} onClose={()=>setSelected(null)} onApprove={approve} onReject={reject} onDelete={deleteApplication}/>}</main></Shell>
}

function buildFinance(loans,payments){
  const released=loans.filter(l=>['ATIVO','PAGO'].includes(l.status));let capitalReleased=0,contracted=0,received=0,receivable=0,realizedProfit=0,projectedProfit=0,principalRecovered=0,overdue=0;
  released.forEach(l=>{const principal=Number(l.principal||0),total=Number(l.total_amount||principal),count=Number(l.installment_count||2)||2,interest=Math.max(0,total-principal);capitalReleased+=principal;contracted+=total;projectedProfit+=interest;const lp=payments.filter(p=>String(p.loan_id)===String(l.id));lp.forEach(p=>{const paid=String(p.status||'').startsWith('PAGO');if(paid){received+=Number(p.amount||0);realizedProfit+=interest/count;principalRecovered+=principal/count}else{receivable+=Number(p.amount||0);if(p.status==='PENDENTE'&&new Date(String(p.due_date).slice(0,10)+'T23:59:59')<new Date())overdue+=Number(p.amount||0)}})});
  return{capitalReleased,contracted,received,receivable,realizedProfit,projectedProfit,principalOpen:Math.max(0,capitalReleased-principalRecovered),overdue,activeContracts:released.filter(l=>l.status==='ATIVO').length,paidContracts:released.filter(l=>l.status==='PAGO').length};
}

function WalletDashboard({finance,loans,payments,profileOf}){
  const released=loans.filter(l=>['ATIVO','PAGO'].includes(l.status));
  const rows=released.map(l=>{const lp=payments.filter(p=>String(p.loan_id)===String(l.id)),received=lp.filter(p=>String(p.status||'').startsWith('PAGO')).reduce((a,p)=>a+Number(p.amount||0),0),toReceive=lp.filter(p=>p.status==='PENDENTE').reduce((a,p)=>a+Number(p.amount||0),0),profit=Math.max(0,Number(l.total_amount||0)-Number(l.principal||0)),next=lp.filter(p=>p.status==='PENDENTE').sort((a,b)=>String(a.due_date).localeCompare(String(b.due_date)))[0];return{l,received,toReceive,profit,next}});
  const progress=finance.contracted?Math.min(100,(finance.received/finance.contracted)*100):0;
  return <section className="wallet-page"><div className="wallet-hero"><div><small>CARTEIRA W.I.L PAY</small><h2>{brl(finance.principalOpen)}</h2><p>Capital ainda em carteira ativa</p></div><div className="wallet-profit"><small>LUCRO REALIZADO</small><b>{brl(finance.realizedProfit)}</b><span>Projetado: {brl(finance.projectedProfit)}</span></div></div><div className="wallet-grid"><article><small>CAPITAL LIBERADO</small><b>{brl(finance.capitalReleased)}</b><span>Total enviado aos clientes</span></article><article><small>RECEBIDO</small><b>{brl(finance.received)}</b><span>Parcelas já pagas</span></article><article><small>A RECEBER</small><b>{brl(finance.receivable)}</b><span>Saldo dos contratos</span></article><article><small>ATRASADO</small><b>{brl(finance.overdue)}</b><span>Parcelas vencidas</span></article><article><small>CONTRATOS ATIVOS</small><b>{finance.activeContracts}</b><span>{finance.paidContracts} quitados</span></article><article><small>RETORNO DA CARTEIRA</small><b>{progress.toFixed(1)}%</b><span>Recebido sobre contratado</span></article></div><div className="wallet-progress"><div><b>Fluxo da carteira</b><span>{brl(finance.received)} de {brl(finance.contracted)}</span></div><i><em style={{width:`${progress}%`}}/></div><section className="panel wallet-table-wrap"><small>CARTEIRA POR CLIENTE</small><h2>Contratos</h2>{rows.length?<div className="wallet-table"><div className="wallet-tr wallet-head"><span>Cliente</span><span>Liberado</span><span>Recebido</span><span>A receber</span><span>Lucro</span><span>Próximo</span></div>{rows.map(({l,received,toReceive,profit,next})=><div className="wallet-tr" key={l.id}><span><b>{profileOf(l.auth_uid).name}</b><small>{l.status==='PAGO'?'Quitado':'Ativo'}</small></span><span>{brl(l.principal)}</span><span>{brl(received)}</span><span>{brl(toReceive)}</span><span>{brl(profit)}</span><span>{next?fmtDate(next.due_date):'—'}</span></div>)}</div>:<div className="empty">A carteira aparece depois da primeira liberação.</div>}</section></section>;
}

function ClientFileModal({loan,profile,docs,point,busy,onClose,onApprove,onReject,onDelete}){
  const a=loan.answers||{},[approved,setApproved]=useState(String(loan.approved_principal||loan.principal||'')),base=baseDocTypes.filter(t=>docs.some(d=>d.doc_type===t)).length,guar=guaranteeDocTypes.filter(t=>docs.some(d=>d.doc_type===t)).length,ready=base===3&&!!point&&(!loan.collateral_required||guar===3),labels={amount:'Valor solicitado',purpose:'Finalidade',income_type:'Fonte de renda',monthly_income:'Renda mensal',income_time:'Tempo de renda',open_debts:'Parcelas em aberto'};
  return <div className="modal-backdrop" onClick={onClose}><div className="modal wide" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><small>FICHA DO CLIENTE · #{loan.id}</small><h2>{profile.name}</h2><div className="score-inline"><span className={`grade grade-${grade(profile.score)}`}>{grade(profile.score)}</span><b>{profile.score} pontos · {gradeText(profile.score)}</b></div>{!ready&&<div className="error">Ficha incompleta: {base}/3 documentos · localização {point?'OK':'faltando'}{loan.collateral_required?` · garantia ${guar}/3`:''}. A aprovação está bloqueada.</div>}<h3>Respostas</h3><div className="answers">{Object.entries(a).filter(([k])=>!k.includes('contact_')).map(([k,v])=><span key={k}><small>{labels[k]||k}</small><b>{k==='amount'||k==='monthly_income'?brl(v):String(v)}</b></span>)}</div><h3>Contatos obrigatórios</h3><div className="contact-review"><article><small>TRABALHO</small><b>{a.work_contact_name||'—'}</b><span>{a.work_contact_phone||'—'}</span></article><article><small>FAMÍLIA</small><b>{a.family_contact_name||'—'}</b><span>{a.family_contact_phone||'—'}</span></article></div>{loan.collateral_required&&<><h3>Garantia</h3><div className="guarantee-summary"><span><small>Descrição</small><b>{loan.collateral_description||'—'}</b></span><span><small>Valor informado</small><b>{brl(loan.collateral_declared_value)}</b></span><span><small>Status físico</small><b>{loan.collateral_received_at?'Recebida em mãos':'Ainda não recebida'}</b></span></div>{loan.status==='EM_ANALISE'&&<label className="approval-value">VALOR QUE VOCÊ VAI LIBERAR<input type="number" min="100" max={loan.principal} value={approved} onChange={e=>setApproved(e.target.value)}/></label>}</>}<h3>Documentos e fotos</h3><div className="doc-preview-grid">{docs.filter(d=>d.doc_type!=='COMPROVANTE_PAGAMENTO').length?docs.filter(d=>d.doc_type!=='COMPROVANTE_PAGAMENTO').map(d=><DocumentViewer key={d.id||d.doc_type} doc={d}/>):<div className="empty">Nenhum documento salvo.</div>}</div>{docs.some(d=>d.doc_type==='COMPROVANTE_PAGAMENTO')&&<><h3>Comprovante da liberação</h3><div className="doc-preview-grid">{docs.filter(d=>d.doc_type==='COMPROVANTE_PAGAMENTO').map(d=><DocumentViewer key={d.id} doc={d}/>)}</div></>}<h3>Localização autorizada</h3>{point?<><MapView point={point}/><p className="map-meta">Capturada em {fmtDateTime(point.captured_at)} · precisão aproximada {Math.round(point.accuracy||0)} m</p></>:<div className="empty">Sem localização registrada.</div>}<div className="modal-actions"><button className="danger" disabled={busy} onClick={()=>onDelete(loan)}>Excluir</button>{loan.status==='EM_ANALISE'&&<><button className="danger" disabled={busy} onClick={()=>onReject(loan)}>Recusar</button><button className="primary" disabled={busy||!ready} onClick={()=>onApprove(loan,approved)}>Aprovar e pedir PIX</button></>}</div></div></div>
}
function DocumentViewer({doc}){const image=String(doc.mime_type||'').startsWith('image/');return <article className="doc-card"><div className="doc-thumb">{image?<img src={doc.data_url} alt={docTitle(doc.doc_type)}/>:<div className="pdf-badge">PDF</div>}</div><b>{docTitle(doc.doc_type)}</b><small>{doc.file_name||'Arquivo enviado'}</small><a href={doc.data_url} target="_blank" rel="noreferrer">Abrir documento</a></article>}
function MapView({point}){if(!point)return null;const lat=Number(point.latitude),lon=Number(point.longitude),src=`https://www.openstreetmap.org/export/embed.html?bbox=${lon-.005}%2C${lat-.004}%2C${lon+.005}%2C${lat+.004}&layer=mapnik&marker=${lat}%2C${lon}`;return <div className="real-map"><iframe title="Localização do cliente" src={src}/></div>}
function Deadline({deadline}){const ms=new Date(deadline)-new Date(),hours=Math.max(0,Math.ceil(ms/3600000)),expired=ms<0;return <div className={expired?'deadline-badge expired':'deadline-badge'}><small>{expired?'PRAZO VENCIDO':'TEMPO RESTANTE'}</small><b>{expired?'0h':`${hours}h`}</b><span>{fmtDateTime(deadline)}</span></div>}
